// 개발 환경의 Playwright로 실행하는 실제 브라우저 검증. 앱 실행에는 필요하지 않다.
const { chromium } = require(process.env.PLAYWRIGHT_PACKAGE || 'playwright');
const assert = require('node:assert/strict');
const fs = require('node:fs/promises');
const path = require('node:path');
const { pathToFileURL } = require('node:url');

(async () => {
  const output = path.resolve(__dirname, '../test-artifacts'); await fs.mkdir(output, {recursive:true});
  const browser = await chromium.launch({headless:true, executablePath:process.env.CHROME_PATH || 'C:/Program Files/Google/Chrome/Application/chrome.exe'});
  const context = await browser.newContext({viewport:{width:1440,height:1100}, acceptDownloads:true});
  const page = await context.newPage(), errors = [];
  page.on('pageerror', error => errors.push(error.message));
  page.on('console', message => { if (message.type() === 'error') errors.push(message.text()); });
  const checks = []; const pass = name => { checks.push(name); console.log(`PASS ${name}`); };
  try {
    const targetURL = process.env.PORTABLE_TEST === '1'
      ? pathToFileURL(path.resolve(__dirname, '../점도_검토실_바로열기.html')).href
      : 'http://127.0.0.1:4173';
    await page.goto(targetURL);
    await page.waitForFunction(() => document.getElementById('total-count').textContent === '1,080');
    assert.equal(await page.locator('#pass-count').innerText(), '432');
    assert.equal(await page.locator('#review-count').innerText(), '648');
    assert.equal(await page.locator('#chart circle').count(), 648);
    assert.equal(await page.locator('.comparison-guide .guide-item').count(), 3);
    assert.ok((await page.locator('.follow-up-empty').innerText()).includes('추가 확인할 차이·누락'));
    assert.equal(await page.locator('.comparison-guide .guide-item[data-field="viscosity"] .guide-expected span').innerText(), '1000~1500 mPa·s');
    pass('1,080건 로딩과 실제 화면 집계·그래프');
    await page.screenshot({path:path.join(output,'desktop.png'), fullPage:true});

    const comparison = page.locator('details.comparison-section');
    const comparisonSummary = comparison.locator('summary');
    assert.equal(await comparison.getAttribute('open'), null);
    assert.equal(await page.locator('.comparison-scroll').isVisible(), false);
    assert.equal(await page.locator('.follow-up-section').isVisible(), true);
    await page.locator('#detail').screenshot({path:path.join(output,'comparison-collapsed-desktop.png')});
    await comparisonSummary.press('Enter');
    assert.equal(await page.locator('.comparison-scroll').isVisible(), true);
    assert.equal(await page.locator('.comparison-row').count(), 40);
    await comparisonSummary.press('Space');
    assert.equal(await page.locator('.comparison-scroll').isVisible(), false);
    await comparisonSummary.click();
    assert.equal(await page.locator('.comparison-scroll').isVisible(), true);
    pass('기록·기준 비교표 기본 접힘·클릭과 키보드로 펼치기·접기·아래 체크리스트 표시');

    const chartPoint = id => page.locator('.chart-point').filter({has:page.locator('title', {hasText:id+':'})});
    const assertChartSelection = async (id, pageNumber) => {
      assert.equal(await page.locator('.detail-top h3').innerText(), id);
      assert.ok((await page.locator('#page-label').innerText()).startsWith(pageNumber+' /'));
      assert.ok((await page.locator('#record-rows tr.selected').innerText()).includes(id));
      assert.equal(await chartPoint(id).getAttribute('aria-pressed'), 'true');
      assert.equal(await page.evaluate(() => document.activeElement.id), 'detail');
      assert.equal(await comparison.evaluate(node => node.open), true);
      const bounds = await page.locator('#detail').boundingBox();
      assert.ok(bounds.y >= 0 && bounds.y < page.viewportSize().height);
    };
    await chartPoint('PA-008-M4').click();
    await assertChartSelection('PA-008-M4',4);
    await page.locator('#detail').screenshot({path:path.join(output,'chart-navigation-detail.png')});
    await page.locator('#search').fill('PA-008');
    await page.locator('#status-filter').selectOption('review');
    await page.locator('#category-filter').selectOption('specification');
    await chartPoint('PA-008-M1').press('Enter');
    await assertChartSelection('PA-008-M1',1);
    assert.equal(await page.locator('#search').inputValue(),'PA-008');
    assert.equal(await page.locator('#status-filter').inputValue(),'review');
    assert.equal(await page.locator('#category-filter').inputValue(),'specification');
    await chartPoint('PA-008-M3').press('Space');
    await assertChartSelection('PA-008-M3',1);
    await page.locator('.chart-panel').screenshot({path:path.join(output,'chart-navigation-desktop.png')});
    await page.locator('#reset-filter').click();
    pass('그래프 점 클릭·Enter·Space로 정확한 반복값 선택·페이지 이동·검색 필터 유지');

    await page.locator('#search').fill('PA-006');
    assert.equal(await page.locator('#record-rows tr').count(), 4);
    assert.ok((await page.locator('#detail').innerText()).includes('비교 조건 확인 필요'));
    assert.equal(await page.locator('.comparison-guide .guide-item[data-field="sampleTemperature"] .guide-actual span').innerText(), '28 ℃');
    assert.equal(await page.locator('.comparison-guide .guide-item[data-field="sampleTemperature"] .guide-expected span').innerText(), '25 ± 0.5 ℃');
    await page.locator('.comparison-guide').screenshot({path:path.join(output,'guidance-desktop.png')});
    await page.locator('.record-link').nth(1).click();
    assert.ok((await page.locator('#detail').innerText()).includes('측정 속도 (rpm)'));
    const rpmRow = page.locator('.comparison-row[data-field="rpm"]');
    assert.equal(await rpmRow.locator('.comparison-actual').innerText(), '30');
    assert.equal(await rpmRow.locator('.comparison-expected').innerText(), '60 rpm');
    assert.ok((await rpmRow.locator('.comparison-status').innerText()).includes('조건 차이'));
    assert.equal(await page.locator('.follow-up-task').count(), 1);
    assert.ok((await page.locator('.follow-up-question').innerText()).includes('회전 속도'));
    await page.locator('.follow-up-check input').check();
    assert.equal(await page.locator('.follow-up-progress').innerText(), '확인 완료 1개 · 확인 불가 0개 · 미확인 0개');
    assert.ok((await page.locator('.detail-top .badge').innerText()).includes('검토 필요'));
    await page.locator('.follow-up-section').screenshot({path:path.join(output,'checklist-desktop.png')});
    assert.equal(await page.locator('.comparison-guide .guide-item').count(), 1);
    assert.equal(await page.locator('.comparison-guide .guide-actual span').innerText(), '30 rpm');
    pass('배치 검색·반복 기록 선택·실제 값과 기준 이유');

    assert.equal(await page.locator('.comparison-row').count(), 40);
    await page.locator('#comparison-only-issues').check();
    assert.equal(await page.locator('.comparison-row').count(), 1);
    await page.screenshot({path:path.join(output,'comparison-desktop.png'), fullPage:true});
    await page.locator('.comparison-section').screenshot({path:path.join(output,'comparison-panel-desktop.png')});
    await page.locator('#search').fill('PA-001');
    assert.ok((await page.locator('.comparison-empty').innerText()).includes('차이·누락이 없습니다'));
    await page.locator('#comparison-only-issues').uncheck();
    assert.equal(await page.locator('.comparison-row[data-field="sourceNote"] .badge').innerText(), '기록 있음');
    await page.locator('#search').fill('PA-007');
    assert.equal(await page.locator('.comparison-row[data-field="sampleTemperature"] .comparison-actual').innerText(), '미기재');
    assert.equal(await page.locator('.comparison-row[data-field="sampleTemperature"] .comparison-expected').innerText(), '25 ± 0.5 ℃');
    assert.equal(await page.locator('.comparison-guide .guide-actual span').innerText(), '미기재');
    const missingTask = page.locator('.follow-up-task[data-task="missing:sampleTemperature"]');
    await missingTask.locator('input').check();
    await missingTask.locator('.follow-up-unavailable').click();
    assert.equal(await missingTask.locator('input').isChecked(), false);
    assert.equal(await missingTask.locator('.follow-up-status').innerText(), '확인 불가');
    await missingTask.locator('.follow-up-reason').fill('원본 기록에 측정 온도가 없어 확인할 수 없음');
    assert.equal(await missingTask.locator('.follow-up-reason-category option').count(), 6);
    await missingTask.locator('.follow-up-reason-category').selectOption('필요한 항목 미기록');
    assert.ok((await page.locator('.detail-top .badge').innerText()).includes('검토 필요'));
    await page.locator('.follow-up-section').screenshot({path:path.join(output,'unavailable-desktop.png')});
    await page.reload(); await page.waitForFunction(() => document.getElementById('total-count').textContent === '1,080');
    await comparisonSummary.click();
    await page.locator('#search').fill('PA-007');
    assert.equal(await missingTask.locator('.follow-up-status').innerText(), '확인 불가');
    assert.equal(await missingTask.locator('.follow-up-reason').inputValue(), '원본 기록에 측정 온도가 없어 확인할 수 없음');
    assert.equal(await missingTask.locator('.follow-up-reason-category').inputValue(), '필요한 항목 미기록');
    const [unavailableReport] = await Promise.all([page.waitForEvent('download'), page.locator('#export-report').click()]);
    const unavailableReportText = await fs.readFile(await unavailableReport.path(), 'utf8');
    assert.ok(unavailableReportText.includes('상태: 확인 불가')); assert.ok(unavailableReportText.includes('원본 기록에 측정 온도가 없어 확인할 수 없음'));
    assert.ok(unavailableReportText.includes('필요한 항목 미기록')); assert.ok(unavailableReportText.includes('확인 불가 이유별 모아보기'));
    const [unavailableCSV] = await Promise.all([page.waitForEvent('download'), page.locator('#export-csv').click()]);
    assert.ok((await fs.readFile(await unavailableCSV.path(), 'utf8')).includes('""status"":""unavailable""'));
    await missingTask.locator('.follow-up-unavailable').click();
    assert.equal(await missingTask.locator('.follow-up-status').innerText(), '미확인');
    assert.equal(await missingTask.locator('.follow-up-reason').isVisible(), false);
    await missingTask.locator('input').check();
    assert.equal(await missingTask.locator('.follow-up-status').innerText(), '자료 확인 완료');
    assert.equal(await missingTask.locator('.follow-up-unavailable').getAttribute('aria-pressed'), 'false');
    await missingTask.locator('input').uncheck();
    await missingTask.locator('.follow-up-unavailable').click();
    await missingTask.locator('.follow-up-reason').fill('원본 기록에 측정 온도가 없어 확인할 수 없음');
    pass('확인 불가 상태·이유·저장·완료와 전환·판정 유지·보고서와 CSV 보존');
    await missingTask.locator('.follow-up-manage-categories').click();
    await page.locator('#reason-category-name').fill('  '); await page.locator('.category-add-button').click();
    assert.ok((await page.locator('#reason-category-error').innerText()).includes('입력하세요'));
    await page.locator('#reason-category-name').fill('추가 자료 필요'); await page.locator('.category-add-button').click();
    assert.ok((await page.locator('#reason-category-error').innerText()).includes('이미 있는'));
    await page.locator('#reason-category-name').fill('장비 점검 자료 없음'); await page.locator('.category-add-button').click();
    assert.equal(await missingTask.locator('.follow-up-reason-category').inputValue(), '장비 점검 자료 없음');
    await page.locator('#unavailable-summary > summary').click();
    await page.locator('#unavailable-filter').selectOption('장비 점검 자료 없음');
    assert.equal(await page.locator('.unavailable-entry').count(), 1);
    assert.ok((await page.locator('.unavailable-entry-note').innerText()).includes('측정 온도가 없어'));
    await page.locator('#unavailable-summary').screenshot({path:path.join(output,'reason-categories-desktop.png')});
    const [reasonCSV] = await Promise.all([page.waitForEvent('download'), page.locator('#export-unavailable').click()]);
    const reasonCSVText = await fs.readFile(await reasonCSV.path(), 'utf8');
    assert.ok(reasonCSVText.includes('장비 점검 자료 없음')); assert.ok(reasonCSVText.includes('PA-007-M1')); assert.ok(reasonCSVText.includes('측정 온도가 없어'));
    await page.locator('#search').fill('PA-001');
    assert.equal(await page.locator('.unavailable-entry').count(), 1);
    await page.locator('.unavailable-open-record').click();
    assert.equal(await page.locator('.detail-top h3').innerText(), 'PA-007-M1');
    pass('이유 분류 추가·중복 거부·선택 저장·이유별 모아보기·원본 이동·분류 CSV');
    await page.evaluate(() => {
      const original = JSON.parse(localStorage.getItem('poly-checklists-demo-20261002'))['PA-007-M1'];
      const other = JSON.parse(JSON.stringify(original));
      other.outcomes['missing:sampleTemperature'].reason = '다른 파일의 메모';
      localStorage.setItem('poly-checklists-category-delete-test', JSON.stringify({'PA-007-M1': other}));
    });
    await page.locator('#manage-reason-categories').click();
    await page.getByRole('button', {name:'장비 점검 자료 없음 분류 삭제', exact:true}).click();
    await page.getByRole('button', {name:'기타 분류 삭제', exact:true}).click();
    await page.locator('#close-reason-categories').click();
    assert.equal(await missingTask.locator('.follow-up-reason-category').inputValue(), '');
    assert.equal(await missingTask.locator('.follow-up-reason').inputValue(), '원본 기록에 측정 온도가 없어 확인할 수 없음');
    const otherOutcome = await page.evaluate(() => JSON.parse(localStorage.getItem('poly-checklists-category-delete-test'))['PA-007-M1'].outcomes['missing:sampleTemperature']);
    assert.equal(otherOutcome.reasonCategory, ''); assert.equal(otherOutcome.reason, '다른 파일의 메모'); assert.equal(otherOutcome.status, 'unavailable');
    await page.locator('#unavailable-filter').selectOption('미분류');
    assert.equal(await page.locator('.unavailable-entry').count(), 1);
    await page.reload(); await page.waitForFunction(() => document.getElementById('total-count').textContent === '1,080');
    await comparisonSummary.click();
    await page.locator('#search').fill('PA-007');
    assert.equal(await missingTask.locator('.follow-up-reason').inputValue(), '원본 기록에 측정 온도가 없어 확인할 수 없음');
    assert.equal(await missingTask.locator('.follow-up-reason-category option').count(), 5);
    await missingTask.locator('.follow-up-manage-categories').click();
    await page.locator('#reason-category-name').fill('기타'); await page.locator('.category-add-button').click();
    await missingTask.locator('.follow-up-reason-category').selectOption('필요한 항목 미기록');
    pass('분류 삭제·재접속 후 유지·기존 및 다른 파일의 메모와 상태 보존·미분류 이동');
    await page.locator('#search').fill('PA-008');
    assert.equal(await page.locator('.comparison-row[data-field="viscosity"] .badge').innerText(), '범위 이탈');
    assert.equal(await page.locator('.follow-up-task').count(), 1);
    assert.ok((await page.locator('.follow-up-question').innerText()).includes('조건 차이는 발견되지 않았어요'));
    assert.ok((await page.locator('.follow-up-question').innerText()).includes('원인을 알 수 없어 추가 자료가 필요'));
    assert.equal(await page.locator('.follow-up-status').innerText(), '미확인');
    await page.locator('.follow-up-section').screenshot({path:path.join(output,'unexplained-viscosity-desktop.png')});
    pass('점도만 이탈: 기록상 조건 차이 없음·원인 판단 보류·추가 자료 안내');
    await page.locator('#search').fill('PA-006'); await page.locator('.record-link').nth(1).click();
    pass('40항목 비교표·차이 필터·기록 전용·누락·범위 이탈 구분');

    await page.locator('#review-note').fill('측정 방법 확인 후 검토합니다.');
    const [report] = await Promise.all([page.waitForEvent('download'), page.locator('#export-report').click()]);
    const reportText = await fs.readFile(await report.path(), 'utf8');
    assert.ok(reportText.includes('측정 방법 확인 후 검토합니다.'));
    assert.ok(reportText.includes('temperatureTolerance'));
    assert.ok(reportText.includes('대상 측정: 4건'));
    assert.ok(reportText.includes('- [x] 측정 속도'));
    const [csv] = await Promise.all([page.waitForEvent('download'), page.locator('#export-csv').click()]);
    const csvText = await fs.readFile(await csv.path(), 'utf8');
    assert.ok(csvText.includes('criteriaSnapshot')); assert.ok(csvText.includes('측정 방법 확인 후 검토합니다.'));
    assert.ok(csvText.includes('followUpChecklist')); assert.ok(csvText.includes('""checked"":true'));
    pass('실제 CSV·Markdown 다운로드에 필터·전체 기준·메모 포함');
    const [template] = await Promise.all([page.waitForEvent('download'), page.locator('#download-template').click()]);
    const templateText = await fs.readFile(await template.path(), 'utf8');
    assert.ok(templateText.includes('PA-270-M4'));
    assert.ok(templateText.startsWith('\uFEFF"batchId"'));
    pass('서버 연결 없이도 입력 양식 다운로드');

    await page.locator('#reset-filter').click();
    await page.locator('#category-filter').selectOption('missing');
    assert.ok((await page.locator('#filtered-count').innerText()).includes('108건'));
    await page.locator('#reset-filter').click();
    await page.locator('#search').fill('없는배치');
    assert.ok((await page.locator('#record-rows').innerText()).includes('해당하는 기록이 없습니다'));
    assert.equal(await page.locator('#export-report').isDisabled(), true);
    await page.locator('#reset-filter').click();
    await page.locator('#next-page').click();
    assert.ok((await page.locator('#page-label').innerText()).startsWith('2 /'));
    pass('누락 필터·검색 결과 없음·페이지 이동');

    await page.locator('#search').fill('PA-006'); await page.locator('.record-link').nth(1).click();
    assert.equal(await page.locator('.follow-up-check input').isChecked(), true);
    await page.reload(); await page.waitForFunction(() => document.getElementById('total-count').textContent === '1,080');
    await comparisonSummary.click();
    await page.locator('#search').fill('PA-006'); await page.locator('.record-link').nth(1).click();
    assert.equal(await page.locator('.follow-up-check input').isChecked(), true);

    await page.locator('#open-criteria').click();
    await page.locator('#criterion-viscosityMin').fill('2000');
    await page.locator('#criteria-form button[type=submit]').click();
    assert.ok((await page.locator('#criteria-error').innerText()).includes('하한은 상한보다'));
    await page.locator('#criterion-viscosityMin').fill('1000');
    await page.locator('#criterion-viscosityMax').fill('1250');
    await page.locator('#criteria-form button[type=submit]').click();
    assert.notEqual(await page.locator('#pass-count').innerText(), '432');
    assert.equal(await page.locator('.follow-up-task[data-task="measurement:rpm"] input').isChecked(), false);
    assert.equal(await page.locator('.comparison-row[data-field="viscosity"] .comparison-expected').innerText(), '1000~1250 mPa·s');
    await page.locator('#search').fill('PA-007');
    assert.equal(await missingTask.locator('.follow-up-status').innerText(), '미확인');
    assert.equal(await missingTask.locator('.follow-up-reason').isVisible(), false);
    await page.locator('#search').fill('PA-008');
    assert.equal(await page.locator('.comparison-guide .guide-item[data-field="viscosity"] .guide-expected span').innerText(), '1000~1250 mPa·s');
    const version = await page.locator('#criteria-version').innerText();
    await page.reload(); await page.waitForFunction(() => document.getElementById('total-count').textContent === '1,080');
    await comparisonSummary.click();
    assert.equal(await page.locator('#criteria-version').innerText(), version);
    await page.locator('#search').fill('PA-006'); await page.locator('.record-link').nth(1).click();
    assert.equal(await page.locator('#review-note').inputValue(), '측정 방법 확인 후 검토합니다.');
    pass('잘못된 기준 거부·기준 변경 재검토·새로고침 후 기준과 메모 유지');

    await page.locator('#open-criteria').click(); await page.locator('#reset-criteria').click();
    await page.locator('#criteria-form button[type=submit]').click();
    const data = JSON.parse(await fs.readFile(path.join(__dirname,'../data/demo-records.json'),'utf8'));
    const original = await fs.readFile(path.join(__dirname,'../data/demo-records.csv'),'utf8');
    await page.locator('#csv-file').setInputFiles({name:'가상자료.csv', mimeType:'text/csv', buffer:Buffer.from(original)});
    await page.waitForFunction(() => document.getElementById('source-name').textContent === '가상자료.csv');
    assert.equal(await page.locator('#total-count').innerText(), '1,080');
    await page.locator('#search').fill('PA-006'); await page.locator('.record-link').nth(1).click();
    assert.equal(await page.locator('.follow-up-check input').isChecked(), false);
    await page.locator('#csv-file').setInputFiles({name:'중복.csv', mimeType:'text/csv', buffer:Buffer.from('batchId,measurementId,viscosity,unit\nb,m,1200,cP\nb,m,1300,cP')});
    await page.waitForFunction(() => document.getElementById('message').textContent.includes('중복 측정 번호'));
    assert.equal(await page.locator('#total-count').innerText(), '1,080');
    pass('실제 CSV 입력·중복 ID 거부·기존 데이터 유지');

    const headers = Object.keys(data[0]);
    const malicious = {...data[0], sourceNote:'<img src=x onerror="window.__injected=true">'};
    const quote = value => `"${String(value).replaceAll('"','""')}"`;
    await page.locator('#csv-file').setInputFiles({name:'문자검증.csv', mimeType:'text/csv', buffer:Buffer.from(headers.join(',')+'\n'+headers.map(key=>quote(malicious[key])).join(','))});
    await page.waitForFunction(() => document.getElementById('total-count').textContent === '1');
    assert.equal(await page.evaluate(() => window.__injected), undefined);
    assert.ok((await page.locator('.comparison-row[data-field="sourceNote"] .comparison-actual').innerText()).includes('<img src=x'));
    pass('CSV의 HTML을 실행하지 않고 원문으로 표시');

    await page.locator('#csv-file').setInputFiles({name:'누락안내.csv', mimeType:'text/csv', buffer:Buffer.from('batchId,measurementId,viscosity,unit\nb,m,1200,cP')});
    await page.waitForFunction(() => document.getElementById('source-name').textContent === '누락안내.csv');
    assert.equal(await page.locator('.comparison-guide > .guide-list .guide-item').count(), 4);
    assert.ok((await page.locator('.guide-more summary').innerText()).includes('나머지'));
    await page.locator('.guide-more summary').click();
    assert.ok(await page.locator('.guide-more .guide-item').count() > 0);
    assert.ok(await page.locator('.follow-up-task').count() > 4);
    assert.ok((await page.locator('.follow-up-list').innerText()).includes('추정값'));
    pass('상단 비교 안내: 정상·차이·누락·기준 변경·여러 확인 항목 표시');
    pass('후속 체크리스트: 자료 확인·저장·판정 유지·기준 변경·데이터 분리·보고서 내보내기');

    await page.locator('#load-demo').click(); await page.waitForFunction(() => document.getElementById('total-count').textContent === '1,080');
    await page.locator('#reset-filter').click();
    for (const width of [390,320]) {
      await page.setViewportSize({width,height:900});
      await page.waitForFunction(() => Number(document.querySelector('#chart svg').viewBox.baseVal.width) === Math.max(280, document.getElementById('chart').clientWidth));
      await page.evaluate(() => window.scrollTo(0,0));
      assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
      assert.equal(await page.locator('.comparison-row[data-field="sampleTemperature"] .comparison-expected').innerText(), '25 ± 0.5 ℃');
      await page.locator('#open-criteria').click();
      assert.equal(await page.evaluate(() => document.querySelector('dialog').getBoundingClientRect().width <= innerWidth), true);
      await page.locator('#close-criteria').click();
      await page.screenshot({path:path.join(output,`mobile-${width}.png`), fullPage:true});
      if (await comparison.evaluate(node => node.open)) await comparisonSummary.click();
      assert.equal(await page.locator('.comparison-scroll').isVisible(), false);
      assert.equal(await page.locator('.follow-up-section').isVisible(), true);
      await page.locator('#search').fill('PA-008');
      assert.equal(await comparison.evaluate(node => node.open), false);
      await comparison.scrollIntoViewIfNeeded();
      await page.screenshot({path:path.join(output,`comparison-collapsed-mobile-${width}.png`)});
      await comparisonSummary.click();
      assert.equal(await page.locator('.comparison-scroll').isVisible(), true);
      await page.locator('#search').fill('PA-008');
      await chartPoint('PA-008-M4').click();
      await assertChartSelection('PA-008-M4',1);
      await page.locator('#reset-filter').click();
    }
    pass('390px·320px 화면에 가로 넘침 없음·기준 창 사용 가능');
    await page.locator('#search').fill('PA-006'); await page.locator('.record-link').nth(1).click();
    await page.locator('#comparison-only-issues').check();
    assert.equal(await page.locator('.comparison-row').count(), 1);
    await page.locator('.comparison-section').scrollIntoViewIfNeeded();
    await page.screenshot({path:path.join(output,'comparison-mobile.png'), fullPage:true});
    await page.locator('.comparison-section').screenshot({path:path.join(output,'comparison-panel-mobile.png')});
    await page.locator('.record-link').first().click();
    await page.locator('.comparison-guide').screenshot({path:path.join(output,'guidance-mobile.png')});
    await page.locator('.follow-up-section').screenshot({path:path.join(output,'checklist-mobile.png')});
    await page.locator('#search').fill('PA-007'); await page.locator('.record-link').first().click();
    await missingTask.locator('input').check(); await missingTask.locator('.follow-up-unavailable').click();
    await missingTask.locator('.follow-up-reason').fill('원본 기록에 측정 온도가 없어 확인할 수 없음');
    await missingTask.locator('.follow-up-reason-category').selectOption('필요한 항목 미기록');
    await page.locator('.follow-up-section').screenshot({path:path.join(output,'unavailable-mobile.png')});
    await page.locator('#unavailable-summary > summary').click();
    await page.locator('#unavailable-summary').screenshot({path:path.join(output,'reason-categories-mobile.png')});
    await page.locator('#manage-reason-categories').click();
    assert.equal(await page.evaluate(() => document.querySelector('#reason-category-dialog').getBoundingClientRect().width <= innerWidth), true);
    await page.locator('#close-reason-categories').click();
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
    const categoryChecksSnapshot = await page.evaluate(() => localStorage.getItem('poly-checklists-demo-20261002'));
    const currentCriteria = await page.evaluate(() => JSON.parse(localStorage.getItem('poly-criteria-v1')));
    const core = await import('../src/core.js');
    const demoRecords = JSON.parse(await fs.readFile(path.resolve(__dirname,'../data/demo-records.json'),'utf8'));
    const categoryChecks = JSON.parse(categoryChecksSnapshot || '{}');
    for (const record of demoRecords.filter(record => record.sampleTemperature === '').slice(0,21)) {
      categoryChecks[record.measurementId] = {signature:core.followUpSignature(record,currentCriteria),outcomes:{'missing:sampleTemperature':{status:'unavailable',reasonCategory:'추가 자료 필요',reason:'페이지 이동 확인용 메모'}}};
    }
    await page.evaluate(checks => localStorage.setItem('poly-checklists-demo-20261002',JSON.stringify(checks)),categoryChecks);
    await page.reload(); await page.waitForFunction(() => document.getElementById('total-count').textContent === '1,080');
    await comparisonSummary.click();
    await page.locator('#unavailable-summary > summary').click();
    await page.locator('#unavailable-filter').selectOption('추가 자료 필요');
    assert.equal(await page.locator('.unavailable-entry').count(),20);
    assert.ok((await page.locator('#unavailable-page-label').innerText()).includes('21개 항목'));
    await page.locator('#unavailable-next').click();
    assert.equal(await page.locator('.unavailable-entry').count(),1);
    await page.locator('#unavailable-previous').click();
    assert.equal(await page.locator('.unavailable-entry').count(),20);
    await page.evaluate(snapshot => localStorage.setItem('poly-checklists-demo-20261002',snapshot),categoryChecksSnapshot);
    pass('이유별 모아보기: 21개 항목의 전체 건수와 페이지 이동');
    assert.deepEqual(errors, []); pass('브라우저 JavaScript·콘솔 오류 없음');
    await fs.writeFile(path.join(output, process.env.PORTABLE_TEST === '1' ? 'portable-results.json' : 'ui-results.json'), JSON.stringify({targetURL,checks,errors},null,2));
  } finally { await browser.close(); }
})().catch(error => { console.error(error); process.exitCode=1; });
