// 개발 환경의 Playwright로 실행하는 실제 브라우저 검증. 앱 실행에는 필요하지 않다.
const { chromium } = require(process.env.PLAYWRIGHT_PACKAGE || 'playwright');
const assert = require('node:assert/strict');
const fs = require('node:fs/promises');
const path = require('node:path');
const { pathToFileURL } = require('node:url');

(async () => {
  const output = path.resolve(__dirname, '../test-artifacts'); await fs.mkdir(output, {recursive:true});
  const browser = await chromium.launch({headless:true, executablePath:process.env.CHROME_PATH || 'C:/Program Files/Google/Chrome/Application/chrome.exe'});
  const context = await browser.newContext({viewport:{width:1440,height:1100}, acceptDownloads:true});
  const page = await context.newPage(), errors = [];
  let downloadCount = 0;
  page.on('download', () => downloadCount++);
  const chooseReportFormat = async format => {
    const before = downloadCount;
    await page.locator('#report-formats > summary').click();
    await page.locator(`[data-report-format="${format}"]`).click();
    await page.waitForEvent('download', {timeout:250}).then(() => assert.fail('형식을 선택하는 동안 다운로드가 발생했습니다.'), error => { if (error.name !== 'TimeoutError') throw error; });
    assert.equal(downloadCount, before);
    assert.equal(await page.locator('#report-download-label').innerText(), `${format === 'txt' ? 'TXT' : 'Markdown'} 내려받기`);
    assert.equal(await page.locator(`[data-report-format="${format}"]`).getAttribute('aria-pressed'), 'true');
    assert.equal(await page.locator('#report-formats').getAttribute('open'), null);
  };
  page.on('pageerror', error => errors.push(error.message));
  page.on('console', message => { if (message.type() === 'error') errors.push(message.text()); });
  const checks = []; const pass = name => { checks.push(name); console.log(`PASS ${name}`); };
  try {
    const targetURL = process.env.PORTABLE_TEST === '1'
      ? pathToFileURL(path.resolve(__dirname, '../점도_검토실_바로열기.html')).href
      : 'http://127.0.0.1:4173';
    await page.goto(targetURL);
    await page.waitForFunction(() => document.getElementById('total-count').textContent === '1,080');
    assert.equal(await page.locator('#pass-count').innerText(), '432');
    assert.equal(await page.locator('#review-count').innerText(), '648');
    assert.equal(await page.locator('#chart circle').count(), 648);
    assert.equal(await page.locator('.comparison-guide .guide-item').count(), 3);
    assert.ok((await page.locator('.follow-up-empty').innerText()).includes('추가 확인할 차이·누락'));
    assert.equal(await page.locator('.comparison-guide .guide-item[data-field="viscosity"] .guide-expected span').innerText(), '1000~1500 mPa·s');
    pass('1,080건 로딩과 실제 화면 집계·그래프');
    await page.screenshot({path:path.join(output,'desktop.png'), fullPage:true});

    const comparison = page.locator('details.comparison-section');
    const comparisonSummary = comparison.locator('.comparison-heading');
    const comparisonGroup = name => page.locator(`.comparison-category[data-group="${name}"]`);
    const groupSummary = name => comparisonGroup(name).locator('summary');
    const expandAllComparisonGroups = () => page.locator('#expand-comparison-groups').click();
    assert.equal(await comparison.getAttribute('open'), null);
    assert.equal(await page.locator('.comparison-scroll:visible').count(), 0);
    assert.equal(await page.locator('.follow-up-section').isVisible(), true);
    await page.locator('#detail').screenshot({path:path.join(output,'comparison-collapsed-desktop.png')});
    await comparisonSummary.press('Enter');
    assert.equal(await page.locator('.comparison-category').count(), 4);
    assert.equal(await page.locator('.comparison-category[open]').count(), 0);
    assert.equal(await page.locator('.comparison-row:visible').count(), 0);
    assert.equal(await page.locator('.comparison-row').count(), 40);
    await groupSummary('점도 결과').press('Enter');
    assert.equal(await page.locator('.comparison-row:visible').count(), 2);
    await groupSummary('측정 조건').press('Space');
    assert.equal(await page.locator('.comparison-row:visible').count(), 16);
    await groupSummary('점도 결과').press('Space');
    assert.equal(await page.locator('.comparison-row:visible').count(), 14);
    await comparisonSummary.press('Space');
    assert.equal(await page.locator('.comparison-scroll:visible').count(), 0);
    await comparisonSummary.click();
    assert.equal(await page.locator('.comparison-row:visible').count(), 14);
    pass('기록·기준 비교표 기본 접힘·클릭과 키보드로 펼치기·접기·아래 체크리스트 표시');
    await page.locator('#collapse-comparison-groups').click();
    assert.equal(await page.locator('.comparison-category[open]').count(), 0);
    for (const [name,count] of [['점도 결과',2],['측정 조건',14],['제조 조건',4],['제품과 나머지 기록',20]]) {
      assert.equal(await comparisonGroup(name).locator('.comparison-row').count(),count);
      assert.ok((await groupSummary(name).innerText()).includes(`${count}항목`));
    }
    await comparison.scrollIntoViewIfNeeded();
    await page.locator('#detail').screenshot({path:path.join(output,'comparison-categories-desktop.png')});
    await groupSummary('측정 조건').click();
    await page.locator('#search').fill('PA-006-M1');
    assert.equal(await comparisonGroup('측정 조건').evaluate(node => node.open),true);
    assert.equal(await comparisonGroup('점도 결과').evaluate(node => node.open),false);
    assert.ok((await groupSummary('측정 조건').innerText()).includes('확인할 항목 1개'));
    await page.locator('#search').fill('PA-006-M2');
    assert.equal(await comparisonGroup('측정 조건').evaluate(node => node.open),true);
    await page.locator('#comparison-only-issues').check();
    assert.equal(await page.locator('.comparison-category').count(),1);
    assert.equal(await page.locator('.comparison-row:visible').count(),1);
    await page.locator('#comparison-only-issues').uncheck();
    assert.equal(await page.locator('.comparison-category').count(),4);
    assert.equal(await comparisonGroup('측정 조건').evaluate(node => node.open),true);
    assert.equal(await comparisonGroup('점도 결과').evaluate(node => node.open),false);
    await page.locator('#collapse-comparison-groups').click();
    assert.equal(await page.locator('.comparison-row:visible').count(),0);
    await expandAllComparisonGroups();
    assert.equal(await page.locator('.comparison-row:visible').count(),40);
    await page.locator('#reset-filter').click();
    pass('비교 카테고리: 4개 독립 접기·항목과 차이 개수·키보드·기록과 필터 변경 유지·모두 펼치기와 접기');

    const chartPoint = id => page.locator('.chart-point').filter({has:page.locator('title', {hasText:id+':'})});
    const assertChartSelection = async (id, pageNumber) => {
      assert.equal(await page.locator('.detail-top h3').innerText(), id);
      assert.ok((await page.locator('#page-label').innerText()).startsWith(pageNumber+' /'));
      assert.ok((await page.locator('#record-rows tr.selected').innerText()).includes(id));
      assert.equal(await chartPoint(id).getAttribute('aria-pressed'), 'true');
      assert.equal(await page.evaluate(() => document.activeElement.id), 'detail');
      assert.equal(await comparison.evaluate(node => node.open), true);
      const bounds = await page.locator('#detail').boundingBox();
      assert.ok(bounds.y >= 0 && bounds.y < page.viewportSize().height);
    };
    await chartPoint('PA-008-M4').click();
    await assertChartSelection('PA-008-M4',4);
    await page.locator('#detail').screenshot({path:path.join(output,'chart-navigation-detail.png')});
    await page.locator('#search').fill('PA-008');
    await page.locator('#status-filter').selectOption('review');
    await page.locator('#category-filter').selectOption('specification');
    await chartPoint('PA-008-M1').press('Enter');
    await assertChartSelection('PA-008-M1',1);
    assert.equal(await page.locator('#search').inputValue(),'PA-008');
    assert.equal(await page.locator('#status-filter').inputValue(),'review');
    assert.equal(await page.locator('#category-filter').inputValue(),'specification');
    await chartPoint('PA-008-M3').press('Space');
    await assertChartSelection('PA-008-M3',1);
    await page.locator('.chart-panel').screenshot({path:path.join(output,'chart-navigation-desktop.png')});
    await page.locator('#reset-filter').click();
    pass('그래프 점 클릭·Enter·Space로 정확한 반복값 선택·페이지 이동·검색 필터 유지');

    const conditionSummary = page.locator('#condition-explorer > summary');
    await conditionSummary.click();
    assert.ok((await page.locator('#condition-preview').innerText()).includes('43~47'));
    await page.locator('#condition-form [type="submit"]').click();
    assert.equal(await page.locator('#filtered-count').innerText(),'현재 216건 / 전체 1,080건');
    assert.equal(await page.locator('#chart circle').count(),108);
    assert.equal(await page.locator('#chart-title').innerText(),'조건별 점도 기록');
    assert.ok((await page.locator('#chart svg').getAttribute('aria-label')).includes('가로축은 제조 온도 (℃)'));
    assert.ok((await page.locator('.record-condition-value').first().innerText()).includes('45 ℃'));
    assert.equal(await page.locator('.detail-top .badge').innerText(),'검토 필요');
    await page.locator('#chart-y-field').selectOption('rpm');
    await page.locator('#chart-axis').selectOption('field:sampleTemperature');
    assert.equal(await page.locator('#filtered-count').innerText(),'현재 216건 / 전체 1,080건');
    assert.equal(await page.locator('#chart circle').count(),108);
    assert.ok((await page.locator('#chart svg').getAttribute('aria-label')).includes('가로축은 실제 측정 온도 (℃), 세로축은 측정 속도 (rpm)'));
    await page.locator('#condition-form [type="submit"]').click();
    assert.equal(await page.locator('#chart-y-field').inputValue(),'rpm');
    assert.equal(await page.locator('#chart-axis').inputValue(),'condition');
    await page.locator('#chart-y-field').selectOption('viscosity');
    const conditionReportEvent = page.waitForEvent('download'); await page.locator('#export-report').click();
    const conditionReport = await conditionReportEvent;
    const conditionText = await fs.readFile(await conditionReport.path(),'utf8');
    assert.ok(conditionText.includes('45 ± 2 (43~47)'));
    assert.ok(conditionText.includes('대상 측정: 216건'));
    assert.equal(conditionText.includes('PA-001-M1'),false);
    await page.locator('.chart-panel').screenshot({path:path.join(output,'condition-chart-desktop.png')});
    await page.locator('#condition-explorer').screenshot({path:path.join(output,'condition-filter-desktop.png')});
    await page.locator('#condition-center').fill('40');
    assert.ok((await page.locator('#condition-summary').innerText()).includes('45 ± 2'));
    assert.equal(await page.locator('#filtered-count').innerText(),'현재 216건 / 전체 1,080건');
    await page.locator('#condition-center').fill('');
    await page.locator('#condition-form [type="submit"]').click();
    assert.equal(await page.locator('#condition-error').isVisible(),true);
    assert.equal(await page.locator('#filtered-count').innerText(),'현재 216건 / 전체 1,080건');
    await page.locator('#condition-center').fill('45'); await page.locator('#condition-tolerance').fill('0');
    await page.locator('#condition-form [type="submit"]').click();
    assert.equal(await page.locator('#filtered-count').innerText(),'현재 216건 / 전체 1,080건');
    await page.locator('#chart-axis').selectOption('batch');
    assert.equal(await page.locator('#chart-title').innerText(),'배치별 점도 기록');
    await page.locator('#chart-axis').selectOption('condition');
    await page.locator('.chart-point[data-measurement-id="PA-005-M1"]').press('Enter');
    assert.equal(await page.locator('.detail-top h3').innerText(),'PA-005-M1');
    assert.ok((await page.locator('#condition-summary').innerText()).includes('45 ± 0'));
    pass('조건 범위: 제조 온도 45±2·216건과 점 108개·판정 유지·미적용 입력과 오류 보존·범위 보고서·가로축 전환과 점 이동');

    await page.locator('#condition-field').selectOption('mixingRpm');
    await page.locator('#condition-limit').uncheck();
    await page.locator('#condition-form [type="submit"]').click();
    assert.equal(await page.locator('#filtered-count').innerText(),'현재 1,080건 / 전체 1,080건');
    assert.ok((await page.locator('#chart-condition-hint').innerText()).includes('모두 300 rpm'));
    await page.locator('#condition-field').selectOption('rpm');
    await page.locator('#condition-limit').check(); await page.locator('#condition-center').fill('30');
    await page.locator('#condition-tolerance').fill('0'); await page.locator('#condition-form [type="submit"]').click();
    assert.equal(await page.locator('#filtered-count').innerText(),'현재 27건 / 전체 1,080건');
    assert.equal(await page.locator('#chart circle').count(),0);
    assert.ok((await page.locator('#chart .empty-detail').innerText()).includes('해제'));
    await page.locator('#comparable-only').uncheck();
    assert.equal(await page.locator('#chart circle').count(),27);
    await page.locator('#status-filter').selectOption('pass');
    assert.equal(await page.locator('#filtered-count').innerText(),'현재 0건 / 전체 1,080건');
    await page.locator('#status-filter').selectOption('all');
    await page.locator('#condition-field').selectOption('spindle');
    await page.locator('#condition-value').selectOption('DEMO-S2');
    await page.locator('#condition-form [type="submit"]').click();
    assert.equal(await page.locator('#filtered-count').innerText(),'현재 27건 / 전체 1,080건');
    assert.equal(await page.locator('#chart circle').count(),27);
    assert.ok((await page.locator('#chart svg').getAttribute('aria-label')).includes('가로축은 스핀들'));
    await page.locator('#clear-condition').click();
    assert.equal(await page.locator('#filtered-count').innerText(),'현재 1,080건 / 전체 1,080건');
    assert.equal(await page.locator('.record-condition-value').count(),0);
    assert.equal(await page.locator('#chart-axis-controls').isVisible(),true);
    assert.equal(await page.locator('#chart-axis option[value="condition"]').evaluate(option=>option.disabled),true);
    await page.locator('#comparable-only').check(); await page.locator('#reset-filter').click();
    await conditionSummary.click();
    pass('조건 종류: 교반 속도 전체 값·동일 값 안내·측정 속도와 비교 조건 숨김·기존 필터 교집합·문자 스핀들·해제');

    await page.locator('#search').fill('PA-006'); await page.locator('.record-link').first().click();
    await page.locator('#comparable-only').uncheck();
    const previousMemo = await page.locator('#review-note').inputValue();
    await page.locator('#review-note').fill('축 변경 중 메모 보존 확인');
    await page.locator('.report-record-check').first().check();
    const axisDetail = await page.locator('#detail').innerText();
    const axisPoint = id => page.locator(`.chart-point[data-measurement-id="${id}"]`);
    await page.locator('#chart-axis').selectOption('field:rpm');
    await page.locator('#chart-y-field').selectOption('sampleTemperature');
    assert.equal(await page.locator('#chart-title').innerText(),'조건별 실제 측정 온도 기록');
    assert.equal(await page.locator('#chart circle').count(),4);
    assert.equal(await page.locator('#filtered-count').innerText(),'현재 4건 / 전체 1,080건');
    assert.equal(await page.locator('#detail').innerText(),axisDetail);
    assert.equal(await page.locator('#review-note').inputValue(),'축 변경 중 메모 보존 확인');
    assert.equal(await page.locator('#report-selection-count').innerText(),'보고서에 담을 기록 1건 체크');
    assert.ok(Number(await axisPoint('PA-006-M2').getAttribute('cx')) < Number(await axisPoint('PA-006-M1').getAttribute('cx')));
    assert.ok(Number(await axisPoint('PA-006-M1').getAttribute('cy')) < Number(await axisPoint('PA-006-M2').getAttribute('cy')));
    assert.ok((await axisPoint('PA-006-M1').getAttribute('aria-label')).includes('28 ℃'));
    assert.equal(await page.locator('.chart-spec-limit, .chart-spec-band').count(),0);
    assert.ok((await page.locator('#chart-legend').innerText()).includes('기준 충족'));
    assert.ok((await page.locator('#chart-legend').innerText()).includes('검토 필요'));
    await page.locator('.chart-panel').screenshot({path:path.join(output,'chart-axes-desktop.png')});
    await axisPoint('PA-006-M2').press('Enter'); await assertChartSelection('PA-006-M2',1);
    await page.locator('#chart-axis').selectOption('field:spindle');
    assert.ok((await page.locator('#chart svg').getAttribute('aria-label')).includes('가로축은 스핀들'));
    assert.equal(await page.locator('#chart circle').count(),4);
    await page.locator('#chart-y-field').selectOption('viscosity');
    assert.equal(await page.locator('.chart-spec-limit').count(),2);
    await page.locator('#comparable-only').check();
    await page.locator('.record-link').first().click(); await page.locator('#review-note').fill(previousMemo);
    await page.locator('#clear-report-selection').click(); await page.locator('#report-scope').selectOption('filtered');
    await page.locator('#reset-filter').click();
    assert.equal(await page.locator('#chart-axis').inputValue(),'batch');
    assert.equal(await page.locator('#chart-y-field').inputValue(),'viscosity');
    pass('독립 축 선택: 측정 속도×측정 온도 좌표·문자 가로축·점 이동·점도 기준선 전환·판정/메모/선택 보존');

    await page.locator('#search').fill('PA-006');
    await page.locator('.record-link').first().click();
    assert.equal(await page.locator('#record-rows tr').count(), 4);
    assert.ok((await page.locator('#detail').innerText()).includes('비교 조건 확인 필요'));
    assert.equal(await page.locator('.comparison-guide .guide-item[data-field="sampleTemperature"] .guide-actual span').innerText(), '28 ℃');
    assert.equal(await page.locator('.comparison-guide .guide-item[data-field="sampleTemperature"] .guide-expected span').innerText(), '25 ± 0.5 ℃');
    await page.locator('.comparison-guide').screenshot({path:path.join(output,'guidance-desktop.png')});
    await page.locator('.record-link').nth(1).click();
    assert.ok((await page.locator('#detail').innerText()).includes('측정 속도 (rpm)'));
    const rpmRow = page.locator('.comparison-row[data-field="rpm"]');
    assert.equal(await rpmRow.locator('.comparison-actual').innerText(), '30');
    assert.equal(await rpmRow.locator('.comparison-expected').innerText(), '60 rpm');
    assert.ok((await rpmRow.locator('.comparison-status').innerText()).includes('조건 차이'));
    assert.equal(await page.locator('.follow-up-task').count(), 1);
    assert.ok((await page.locator('.follow-up-question').innerText()).includes('회전 속도'));
    await page.locator('.follow-up-check input').check();
    assert.equal(await page.locator('.follow-up-progress').innerText(), '확인 완료 1개 · 확인 불가 0개 · 미확인 0개');
    assert.ok((await page.locator('.detail-top .badge').innerText()).includes('검토 필요'));
    await page.locator('.follow-up-section').screenshot({path:path.join(output,'checklist-desktop.png')});
    assert.equal(await page.locator('.comparison-guide .guide-item').count(), 1);
    assert.equal(await page.locator('.comparison-guide .guide-actual span').innerText(), '30 rpm');
    pass('배치 검색·반복 기록 선택·실제 값과 기준 이유');

    const completedNote = page.locator('.follow-up-completion-note');
    assert.equal(await completedNote.isVisible(),true);
    assert.equal(await completedNote.inputValue(),'');
    await completedNote.fill('원본 측정 속도 30 rpm 확인. 추가 사유 확인 필요');
    await page.locator('.follow-up-section').screenshot({path:path.join(output,'completed-note-desktop.png')});
    await page.locator('.follow-up-check input').uncheck();
    assert.equal(await completedNote.isVisible(),false);
    await page.locator('.follow-up-check input').check();
    assert.equal(await completedNote.inputValue(),'원본 측정 속도 30 rpm 확인. 추가 사유 확인 필요');
    await page.locator('.follow-up-unavailable').click();
    await page.locator('.follow-up-manage-categories').click();
    await page.locator('#reason-category-name').fill('완료 메모 보존 검증');
    await page.locator('#reason-category-form button[type="submit"]').click();
    await page.locator('.follow-up-manage-categories').click();
    await page.getByRole('button',{name:'완료 메모 보존 검증 분류 삭제',exact:true}).click();
    await page.locator('#close-reason-categories').click();
    await page.locator('.follow-up-check input').check();
    assert.equal(await completedNote.inputValue(),'원본 측정 속도 30 rpm 확인. 추가 사유 확인 필요');
    await page.reload(); await page.waitForFunction(() => document.getElementById('total-count').textContent === '1,080');
    await page.locator('#search').fill('PA-006-M2');
    assert.equal(await completedNote.inputValue(),'원본 측정 속도 30 rpm 확인. 추가 사유 확인 필요');
    assert.equal(await page.locator('.follow-up-check input').isChecked(),true);
    assert.equal(await page.locator('.detail-top .badge').innerText(),'검토 필요');
    await page.locator('#search').fill('PA-005-M1');
    await page.locator('.follow-up-check input').check();
    assert.equal(await completedNote.inputValue(),'');
    await page.locator('#search').fill('PA-006'); await page.locator('.record-link').nth(1).click();
    await comparisonSummary.click(); await expandAllComparisonGroups();
    pass('확인 완료 메모: 선택 입력·자동 저장·상태 전환과 새로고침 보존·측정별 분리·판정 유지');

    assert.equal(await page.locator('.comparison-row').count(), 40);
    await page.locator('#comparison-only-issues').check();
    assert.equal(await page.locator('.comparison-row').count(), 1);
    await page.screenshot({path:path.join(output,'comparison-desktop.png'), fullPage:true});
    await page.locator('.comparison-section').screenshot({path:path.join(output,'comparison-panel-desktop.png')});
    await page.locator('#search').fill('PA-001');
    assert.ok((await page.locator('.comparison-empty').innerText()).includes('차이·누락이 없습니다'));
    await page.locator('#comparison-only-issues').uncheck();
    assert.equal(await page.locator('.comparison-row[data-field="sourceNote"] .badge').innerText(), '기록 있음');
    await page.locator('#search').fill('PA-007');
    assert.equal(await page.locator('.comparison-row[data-field="sampleTemperature"] .comparison-actual').innerText(), '미기재');
    assert.equal(await page.locator('.comparison-row[data-field="sampleTemperature"] .comparison-expected').innerText(), '25 ± 0.5 ℃');
    assert.equal(await page.locator('.comparison-guide .guide-actual span').innerText(), '미기재');
    const missingTask = page.locator('.follow-up-task[data-task="missing:sampleTemperature"]');
    await missingTask.locator('input').check();
    await missingTask.locator('.follow-up-unavailable').click();
    assert.equal(await missingTask.locator('input').isChecked(), false);
    assert.equal(await missingTask.locator('.follow-up-status').innerText(), '확인 불가');
    await missingTask.locator('.follow-up-reason').fill('원본 기록에 측정 온도가 없어 확인할 수 없음');
    assert.equal(await missingTask.locator('.follow-up-reason-category option').count(), 6);
    await missingTask.locator('.follow-up-reason-category').selectOption('필요한 항목 미기록');
    assert.ok((await page.locator('.detail-top .badge').innerText()).includes('검토 필요'));
    await page.locator('.follow-up-section').screenshot({path:path.join(output,'unavailable-desktop.png')});
    await page.reload(); await page.waitForFunction(() => document.getElementById('total-count').textContent === '1,080');
    await comparisonSummary.click();
    await page.locator('#search').fill('PA-007');
    await expandAllComparisonGroups();
    assert.equal(await missingTask.locator('.follow-up-status').innerText(), '확인 불가');
    assert.equal(await missingTask.locator('.follow-up-reason').inputValue(), '원본 기록에 측정 온도가 없어 확인할 수 없음');
    assert.equal(await missingTask.locator('.follow-up-reason-category').inputValue(), '필요한 항목 미기록');
    await page.locator('#search').fill('PA-007-M1');
    await page.locator('#review-note').fill('원본 온도 기록을 확보한 후 검토합니다.');
    const [plainReport] = await Promise.all([page.waitForEvent('download'), page.locator('#export-report').click()]);
    assert.equal(plainReport.suggestedFilename(), '점도_검토보고서.txt');
    const plainBytes = await fs.readFile(await plainReport.path());
    assert.deepEqual([...plainBytes.subarray(0,3)], [239,187,191]);
    const plainText = plainBytes.toString('utf8');
    for (const expected of ['대상 측정: 1건', 'PA-007-M1', '상태: 확인 불가', '필요한 항목 미기록',
      '원본 기록에 측정 온도가 없어 확인할 수 없음', '원본 온도 기록을 확보한 후 검토합니다.', '목표 측정 온도: 25 ± 0.5 ℃']) assert.ok(plainText.includes(expected));
    assert.equal(plainText.includes('PA-007-M2'), false);
    assert.equal(plainText.includes('```'), false); assert.equal(plainText.includes('temperatureTolerance'), false);
    assert.equal(/(?<!\r)\n/.test(plainText), false);
    const formatSummary = page.locator('#report-formats > summary');
    await formatSummary.focus(); await formatSummary.press('Enter');
    assert.equal(await page.locator('#report-formats').getAttribute('open'), '');
    await page.screenshot({path:path.join(output,'report-formats-desktop.png')});
    await formatSummary.press('Space');
    assert.equal(await page.locator('#report-formats').getAttribute('open'), null);
    await formatSummary.press('Enter'); await page.keyboard.press('Escape');
    assert.equal(await page.locator('#report-formats').getAttribute('open'), null);
    assert.equal(await formatSummary.evaluate(node => document.activeElement === node), true);
    await chooseReportFormat('txt');
    const [menuPlainReport] = await Promise.all([page.waitForEvent('download'), page.locator('#export-report').click()]);
    assert.ok((await fs.readFile(await menuPlainReport.path(),'utf8')).includes('원본 온도 기록을 확보한 후 검토합니다.'));
    assert.equal(await page.locator('#report-formats').getAttribute('open'), null);
    await formatSummary.click(); await page.locator('#filtered-count').click();
    assert.equal(await page.locator('#report-formats').getAttribute('open'), null);
    pass('TXT 다운로드: 1건 범위·분류와 메모·한글 BOM과 줄바꿈·형식 메뉴 키보드와 닫기');
    await page.locator('#search').fill('PA-007');
    await chooseReportFormat('md');
    await formatSummary.click();
    await page.screenshot({path:path.join(output,'report-format-selection-desktop.png')});
    await page.keyboard.press('Escape');
    const [unavailableReport] = await Promise.all([page.waitForEvent('download'), page.locator('#export-report').click()]);
    assert.equal(unavailableReport.suggestedFilename(), '점도_검토보고서.md');
    assert.equal(await page.locator('#report-download-label').innerText(), 'Markdown 내려받기');
    pass('형식 선택 시 다운로드 없음·버튼 이름과 선택 표시 변경·버튼을 눌러 선택한 형식 다운로드');
    const unavailableReportText = await fs.readFile(await unavailableReport.path(), 'utf8');
    assert.ok(unavailableReportText.includes('상태: 확인 불가')); assert.ok(unavailableReportText.includes('원본 기록에 측정 온도가 없어 확인할 수 없음'));
    assert.ok(unavailableReportText.includes('필요한 항목 미기록')); assert.ok(unavailableReportText.includes('확인 불가 이유별 모아보기'));
    const [unavailableCSV] = await Promise.all([page.waitForEvent('download'), page.locator('#export-csv').click()]);
    assert.ok((await fs.readFile(await unavailableCSV.path(), 'utf8')).includes('""status"":""unavailable""'));
    await missingTask.locator('.follow-up-unavailable').click();
    assert.equal(await missingTask.locator('.follow-up-status').innerText(), '미확인');
    assert.equal(await missingTask.locator('.follow-up-reason').isVisible(), false);
    await missingTask.locator('input').check();
    assert.equal(await missingTask.locator('.follow-up-status').innerText(), '자료 확인 완료');
    assert.equal(await missingTask.locator('.follow-up-unavailable').getAttribute('aria-pressed'), 'false');
    await missingTask.locator('input').uncheck();
    await missingTask.locator('.follow-up-unavailable').click();
    await missingTask.locator('.follow-up-reason').fill('원본 기록에 측정 온도가 없어 확인할 수 없음');
    pass('확인 불가 상태·이유·저장·완료와 전환·판정 유지·보고서와 CSV 보존');
    await missingTask.locator('.follow-up-manage-categories').click();
    await page.locator('#reason-category-name').fill('  '); await page.locator('.category-add-button').click();
    assert.ok((await page.locator('#reason-category-error').innerText()).includes('입력하세요'));
    await page.locator('#reason-category-name').fill('추가 자료 필요'); await page.locator('.category-add-button').click();
    assert.ok((await page.locator('#reason-category-error').innerText()).includes('이미 있는'));
    await page.locator('#reason-category-name').fill('장비 점검 자료 없음'); await page.locator('.category-add-button').click();
    assert.equal(await missingTask.locator('.follow-up-reason-category').inputValue(), '장비 점검 자료 없음');
    await page.locator('#unavailable-summary > summary').click();
    await page.locator('#unavailable-filter').selectOption('장비 점검 자료 없음');
    assert.equal(await page.locator('.unavailable-entry').count(), 1);
    assert.ok((await page.locator('.unavailable-entry-note').innerText()).includes('측정 온도가 없어'));
    await page.locator('#unavailable-summary').screenshot({path:path.join(output,'reason-categories-desktop.png')});
    const [reasonCSV] = await Promise.all([page.waitForEvent('download'), page.locator('#export-unavailable').click()]);
    const reasonCSVText = await fs.readFile(await reasonCSV.path(), 'utf8');
    assert.ok(reasonCSVText.includes('장비 점검 자료 없음')); assert.ok(reasonCSVText.includes('PA-007-M1')); assert.ok(reasonCSVText.includes('측정 온도가 없어'));
    await page.locator('#search').fill('PA-001');
    assert.equal(await page.locator('.unavailable-entry').count(), 1);
    await page.locator('.unavailable-open-record').click();
    assert.equal(await page.locator('.detail-top h3').innerText(), 'PA-007-M1');
    pass('이유 분류 추가·중복 거부·선택 저장·이유별 모아보기·원본 이동·분류 CSV');
    await page.evaluate(() => {
      const original = JSON.parse(localStorage.getItem('poly-checklists-demo-20261002'))['PA-007-M1'];
      const other = JSON.parse(JSON.stringify(original));
      other.outcomes['missing:sampleTemperature'].reason = '다른 파일의 메모';
      localStorage.setItem('poly-checklists-category-delete-test', JSON.stringify({'PA-007-M1': other}));
    });
    await page.locator('#manage-reason-categories').click();
    await page.getByRole('button', {name:'장비 점검 자료 없음 분류 삭제', exact:true}).click();
    await page.getByRole('button', {name:'기타 분류 삭제', exact:true}).click();
    await page.locator('#close-reason-categories').click();
    assert.equal(await missingTask.locator('.follow-up-reason-category').inputValue(), '');
    assert.equal(await missingTask.locator('.follow-up-reason').inputValue(), '원본 기록에 측정 온도가 없어 확인할 수 없음');
    const otherOutcome = await page.evaluate(() => JSON.parse(localStorage.getItem('poly-checklists-category-delete-test'))['PA-007-M1'].outcomes['missing:sampleTemperature']);
    assert.equal(otherOutcome.reasonCategory, ''); assert.equal(otherOutcome.reason, '다른 파일의 메모'); assert.equal(otherOutcome.status, 'unavailable');
    await page.locator('#unavailable-filter').selectOption('미분류');
    assert.equal(await page.locator('.unavailable-entry').count(), 1);
    await page.reload(); await page.waitForFunction(() => document.getElementById('total-count').textContent === '1,080');
    await comparisonSummary.click();
    await page.locator('#search').fill('PA-007');
    await expandAllComparisonGroups();
    assert.equal(await missingTask.locator('.follow-up-reason').inputValue(), '원본 기록에 측정 온도가 없어 확인할 수 없음');
    assert.equal(await missingTask.locator('.follow-up-reason-category option').count(), 5);
    await missingTask.locator('.follow-up-manage-categories').click();
    await page.locator('#reason-category-name').fill('기타'); await page.locator('.category-add-button').click();
    await missingTask.locator('.follow-up-reason-category').selectOption('필요한 항목 미기록');
    pass('분류 삭제·재접속 후 유지·기존 및 다른 파일의 메모와 상태 보존·미분류 이동');
    await page.locator('#search').fill('PA-008');
    assert.equal(await page.locator('.comparison-row[data-field="viscosity"] .badge').innerText(), '범위 이탈');
    assert.equal(await page.locator('.follow-up-task').count(), 1);
    assert.ok((await page.locator('.follow-up-question').innerText()).includes('조건 차이는 발견되지 않았어요'));
    assert.ok((await page.locator('.follow-up-question').innerText()).includes('원인을 알 수 없어 추가 자료가 필요'));
    assert.equal(await page.locator('.follow-up-status').innerText(), '미확인');
    await page.locator('.follow-up-section').screenshot({path:path.join(output,'unexplained-viscosity-desktop.png')});
    pass('점도만 이탈: 기록상 조건 차이 없음·원인 판단 보류·추가 자료 안내');
    await page.locator('#search').fill('PA-006'); await page.locator('.record-link').nth(1).click();
    pass('40항목 비교표·차이 필터·기록 전용·누락·범위 이탈 구분');

    await page.locator('#review-note').fill('측정 방법 확인 후 검토합니다.');
    await chooseReportFormat('md');
    const [report] = await Promise.all([page.waitForEvent('download'), page.locator('#export-report').click()]);
    const reportText = await fs.readFile(await report.path(), 'utf8');
    assert.ok(reportText.includes('측정 방법 확인 후 검토합니다.'));
    assert.ok(reportText.includes('temperatureTolerance'));
    assert.ok(reportText.includes('대상 측정: 4건'));
    assert.ok(reportText.includes('- [x] 측정 속도'));
    const [csv] = await Promise.all([page.waitForEvent('download'), page.locator('#export-csv').click()]);
    const csvText = await fs.readFile(await csv.path(), 'utf8');
    assert.ok(csvText.includes('criteriaSnapshot')); assert.ok(csvText.includes('측정 방법 확인 후 검토합니다.'));
    assert.ok(csvText.includes('followUpChecklist')); assert.ok(csvText.includes('""checked"":true'));
    pass('실제 CSV·Markdown 다운로드에 필터·전체 기준·메모 포함');
    const [template] = await Promise.all([page.waitForEvent('download'), page.locator('#download-template').click()]);
    const templateText = await fs.readFile(await template.path(), 'utf8');
    assert.ok(templateText.includes('PA-270-M4'));
    assert.ok(templateText.startsWith('\uFEFF"batchId"'));
    pass('서버 연결 없이도 입력 양식 다운로드');

    const recordCheck = id => page.locator(`.report-record-check[data-measurement-id="${id}"]`);
    await page.locator('#search').fill('PA-006');
    const previousDetailId = await page.locator('.detail-top h3').innerText();
    await recordCheck('PA-006-M2').check();
    assert.equal(await page.locator('.detail-top h3').innerText(), previousDetailId);
    assert.equal(await page.locator('#report-scope').inputValue(), 'selected');
    await page.locator('#search').fill('PA-007'); await recordCheck('PA-007-M1').check();
    assert.equal(await page.locator('#report-selection-count').innerText(), '보고서에 담을 기록 2건 체크');
    await page.locator('.table-panel').screenshot({path:path.join(output,'report-selection-table.png')});
    await page.locator('#search').fill('없는배치');
    assert.equal(await page.locator('#export-csv').isDisabled(), true);
    assert.equal(await page.locator('#export-report').isDisabled(), false);
    await chooseReportFormat('txt');
    const [selectedPlain] = await Promise.all([page.waitForEvent('download'), page.locator('#export-report').click()]);
    assert.equal(selectedPlain.suggestedFilename(), '점도_검토보고서.txt');
    const selectedPlainText = await fs.readFile(await selectedPlain.path(),'utf8');
    await chooseReportFormat('md');
    const [selectedMarkdown] = await Promise.all([page.waitForEvent('download'), page.locator('#export-report').click()]);
    assert.equal(selectedMarkdown.suggestedFilename(), '점도_검토보고서.md');
    const selectedMarkdownText = await fs.readFile(await selectedMarkdown.path(),'utf8');
    for (const text of [selectedPlainText, selectedMarkdownText]) {
      assert.ok(text.includes('대상 측정: 2건')); assert.ok(text.includes('보고서 범위: 체크한 기록 2건'));
      assert.ok(text.includes('PA-006-M2')); assert.ok(text.includes('PA-007-M1'));
      assert.equal(text.includes('PA-007-M2'), false); assert.equal(text.includes('PA-006-M1'), false);
      assert.ok(text.includes('측정 방법 확인 후 검토합니다.')); assert.ok(text.includes('원본 온도 기록을 확보한 후 검토합니다.'));
    }
    await page.locator('#report-scope').selectOption('filtered');
    assert.equal(await page.locator('#export-report').isDisabled(), true);
    await page.locator('#report-scope').selectOption('selected');
    await page.locator('#reset-filter').click();
    await page.locator('#select-visible-records').check();
    assert.equal(await page.locator('.report-record-check:checked').count(), 10);
    await page.locator('#next-page').click(); await page.locator('#select-visible-records').check();
    assert.equal(await page.locator('#report-selection-count').innerText(), '보고서에 담을 기록 22건 체크');
    await page.locator('#previous-page').click(); await page.locator('#select-visible-records').uncheck();
    assert.equal(await page.locator('#report-selection-count').innerText(), '보고서에 담을 기록 12건 체크');
    await page.locator('#clear-report-selection').click();
    assert.equal(await page.locator('#export-report').isDisabled(), true);
    await recordCheck('PA-001-M1').check();
    assert.equal(await page.locator('#select-visible-records').evaluate(node => node.indeterminate), true);
    await recordCheck('PA-001-M1').uncheck();
    assert.equal(await page.locator('#export-report').isDisabled(), true);
    await recordCheck('PA-001-M1').check();
    await page.locator('#load-demo').click();
    await page.waitForFunction(() => document.getElementById('report-scope').value === 'filtered' && document.getElementById('report-selection-count').textContent === '보고서에 담을 기록 0건 체크');
    pass('선택 보고서: 배치·검색·페이지를 넘어 보존·TXT와 Markdown 2건·전체 선택·빈 선택·데이터 전환 초기화');

    await page.locator('#reset-filter').click();
    await page.locator('#category-filter').selectOption('missing');
    assert.ok((await page.locator('#filtered-count').innerText()).includes('108건'));
    await page.locator('#reset-filter').click();
    await page.locator('#search').fill('없는배치');
    assert.ok((await page.locator('#record-rows').innerText()).includes('해당하는 기록이 없습니다'));
    assert.equal(await page.locator('#export-report').isDisabled(), true);
    assert.equal(await page.locator('#report-format-txt').isDisabled(), false);
    assert.equal(await page.locator('#report-format-md').isDisabled(), false);
    await chooseReportFormat('txt');
    assert.equal(await page.locator('#export-report').isDisabled(), true);
    await page.locator('#reset-filter').click();
    await page.locator('#next-page').click();
    assert.ok((await page.locator('#page-label').innerText()).startsWith('2 /'));
    pass('누락 필터·검색 결과 없음·페이지 이동');

    await page.locator('#search').fill('PA-006'); await page.locator('.record-link').nth(1).click();
    assert.equal(await page.locator('.follow-up-check input').isChecked(), true);
    await page.reload(); await page.waitForFunction(() => document.getElementById('total-count').textContent === '1,080');
    await comparisonSummary.click();
    await page.locator('#search').fill('PA-006'); await page.locator('.record-link').nth(1).click();
    await expandAllComparisonGroups();
    assert.equal(await page.locator('.follow-up-check input').isChecked(), true);

    await page.locator('#open-criteria').click();
    await page.locator('#criterion-viscosityMin').fill('2000');
    await page.locator('#criteria-form button[type=submit]').click();
    assert.ok((await page.locator('#criteria-error').innerText()).includes('하한은 상한보다'));
    await page.locator('#criterion-viscosityMin').fill('1000');
    await page.locator('#criterion-viscosityMax').fill('1250');
    await page.locator('#criteria-form button[type=submit]').click();
    assert.notEqual(await page.locator('#pass-count').innerText(), '432');
    assert.equal(await page.locator('.follow-up-task[data-task="measurement:rpm"] input').isChecked(), false);
    assert.equal(await page.locator('.comparison-row[data-field="viscosity"] .comparison-expected').innerText(), '1000~1250 mPa·s');
    await page.locator('#search').fill('PA-007');
    assert.equal(await missingTask.locator('.follow-up-status').innerText(), '미확인');
    assert.equal(await missingTask.locator('.follow-up-reason').isVisible(), false);
    await page.locator('#search').fill('PA-008');
    assert.equal(await page.locator('.comparison-guide .guide-item[data-field="viscosity"] .guide-expected span').innerText(), '1000~1250 mPa·s');
    const version = await page.locator('#criteria-version').innerText();
    await page.reload(); await page.waitForFunction(() => document.getElementById('total-count').textContent === '1,080');
    await comparisonSummary.click();
    assert.equal(await page.locator('#criteria-version').innerText(), version);
    await expandAllComparisonGroups();
    await page.locator('#search').fill('PA-006'); await page.locator('.record-link').nth(1).click();
    assert.equal(await page.locator('#review-note').inputValue(), '측정 방법 확인 후 검토합니다.');
    pass('잘못된 기준 거부·기준 변경 재검토·새로고침 후 기준과 메모 유지');

    await page.locator('#open-criteria').click(); await page.locator('#reset-criteria').click();
    await page.locator('#criteria-form button[type=submit]').click();
    const data = JSON.parse(await fs.readFile(path.join(__dirname,'../data/demo-records.json'),'utf8'));
    const original = await fs.readFile(path.join(__dirname,'../data/demo-records.csv'),'utf8');
    await page.locator('#csv-file').setInputFiles({name:'가상자료.csv', mimeType:'text/csv', buffer:Buffer.from(original)});
    await page.waitForFunction(() => document.getElementById('source-name').textContent === '가상자료.csv');
    assert.equal(await page.locator('#total-count').innerText(), '1,080');
    await page.locator('#search').fill('PA-006'); await page.locator('.record-link').nth(1).click();
    assert.equal(await page.locator('.follow-up-check input').isChecked(), false);
    await page.locator('#csv-file').setInputFiles({name:'중복.csv', mimeType:'text/csv', buffer:Buffer.from('batchId,measurementId,viscosity,unit\nb,m,1200,cP\nb,m,1300,cP')});
    await page.waitForFunction(() => document.getElementById('message').textContent.includes('중복 측정 번호'));
    assert.equal(await page.locator('#total-count').innerText(), '1,080');
    pass('실제 CSV 입력·중복 ID 거부·기존 데이터 유지');

    const headers = Object.keys(data[0]);
    const axisData = [
      {...data[0],measurementId:'AX-A',manufacturingTemperature:-5,sampleTemperature:0,concentration:0.95,viscosity:1200,unit:'cP'},
      {...data[0],measurementId:'AX-B',manufacturingTemperature:5,sampleTemperature:25,concentration:1.05,viscosity:''},
      {...data[0],measurementId:'AX-C',manufacturingTemperature:10,sampleTemperature:'',concentration:1.1,unit:'Pa·s'},
      {...data[0],measurementId:'AX-D',manufacturingTemperature:15,sampleTemperature:'숫자 오류',concentration:1.2,unit:'Pa·s'},
      {...data[0],measurementId:'AX-E',manufacturingTemperature:0,sampleTemperature:-2,concentration:0,viscosity:0,unit:'cP'}
    ];
    const axisQuote = value => `"${String(value).replaceAll('"','""')}"`;
    await page.locator('#csv-file').setInputFiles({name:'축값검증.csv',mimeType:'text/csv',buffer:Buffer.from(headers.join(',')+'\n'+axisData.map(record=>headers.map(key=>axisQuote(record[key])).join(',')).join('\n'))});
    await page.waitForFunction(()=>document.querySelector('#total-count').textContent==='5');
    await page.locator('#comparable-only').uncheck();
    await page.locator('#chart-axis').selectOption('field:manufacturingTemperature');
    await page.locator('#chart-y-field').selectOption('sampleTemperature');
    assert.equal(await page.locator('#chart circle').count(),3);
    assert.equal(await page.locator('#filtered-count').innerText(),'현재 5건 / 전체 5건');
    assert.ok(Number(await axisPoint('AX-B').getAttribute('cy')) < Number(await axisPoint('AX-A').getAttribute('cy')));
    assert.ok(Number(await axisPoint('AX-A').getAttribute('cy')) < Number(await axisPoint('AX-E').getAttribute('cy')));
    assert.equal(await axisPoint('AX-C').count(),0); assert.equal(await axisPoint('AX-D').count(),0);
    assert.equal(await page.locator('.chart-spec-limit').count(),0);
    await page.locator('#chart-y-field').selectOption('concentration');
    assert.equal(await page.locator('#chart circle').count(),5);
    assert.ok((await axisPoint('AX-A').getAttribute('aria-label')).includes('0.95 wt%'));
    await page.locator('#chart-axis').selectOption('field:viscosity');
    assert.equal(await page.locator('#chart circle').count(),2);
    await page.locator('#chart-y-field').selectOption('viscosity');
    assert.equal(await page.locator('#chart circle').count(),2);
    assert.equal(await page.locator('.chart-spec-limit').count(),2);
    const coordinateValues=await page.locator('#chart circle').evaluateAll(nodes=>nodes.flatMap(node=>[node.cx.baseVal.value,node.cy.baseVal.value]));
    assert.ok(coordinateValues.every(Number.isFinite));
    await page.locator('#comparable-only').check();
    pass('축 항목별 결측 제외·점도 없는 측정 온도 표시·0/음수/소수 좌표·cP/미지원 단위·파일 전체 건수 유지');
    const malicious = {...data[0], sourceNote:'<img src=x onerror="window.__injected=true">'};
    const quote = value => `"${String(value).replaceAll('"','""')}"`;
    await page.locator('#csv-file').setInputFiles({name:'문자검증.csv', mimeType:'text/csv', buffer:Buffer.from(headers.join(',')+'\n'+headers.map(key=>quote(malicious[key])).join(','))});
    await page.waitForFunction(() => document.getElementById('total-count').textContent === '1');
    assert.equal(await page.evaluate(() => window.__injected), undefined);
    assert.ok((await page.locator('.comparison-row[data-field="sourceNote"] .comparison-actual').innerText()).includes('<img src=x'));
    pass('CSV의 HTML을 실행하지 않고 원문으로 표시');

    await page.locator('#csv-file').setInputFiles({name:'누락안내.csv', mimeType:'text/csv', buffer:Buffer.from('batchId,measurementId,viscosity,unit\nb,m,1200,cP')});
    await page.waitForFunction(() => document.getElementById('source-name').textContent === '누락안내.csv');
    assert.equal(await page.locator('.comparison-guide > .guide-list .guide-item').count(), 4);
    assert.ok((await page.locator('.guide-more summary').innerText()).includes('나머지'));
    await page.locator('.guide-more summary').click();
    assert.ok(await page.locator('.guide-more .guide-item').count() > 0);
    assert.ok(await page.locator('.follow-up-task').count() > 4);
    assert.ok((await page.locator('.follow-up-list').innerText()).includes('추정값'));
    pass('상단 비교 안내: 정상·차이·누락·기준 변경·여러 확인 항목 표시');
    pass('후속 체크리스트: 자료 확인·저장·판정 유지·기준 변경·데이터 분리·보고서 내보내기');

    await page.locator('#load-demo').click(); await page.waitForFunction(() => document.getElementById('total-count').textContent === '1,080');
    await page.locator('#reset-filter').click();
    for (const width of [390,320]) {
      await page.setViewportSize({width,height:900});
      await chooseReportFormat('md');
      await formatSummary.click();
      const formatBounds = await page.locator('#report-format-options').boundingBox();
      assert.ok(formatBounds.x >= 0 && formatBounds.x + formatBounds.width <= width);
      assert.ok((await formatSummary.boundingBox()).height >= 44);
      assert.ok((await page.locator('#export-report').boundingBox()).height >= 44);
      await page.screenshot({path:path.join(output,`report-formats-mobile-${width}.png`)});
      await page.keyboard.press('Escape');
      await page.setViewportSize({width,height:900});
      await page.waitForFunction(() => Number(document.querySelector('#chart svg').viewBox.baseVal.width) === Math.max(280, document.getElementById('chart').clientWidth));
      await page.evaluate(() => window.scrollTo(0,0));
      assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
      assert.equal(await page.locator('.comparison-row[data-field="sampleTemperature"] .comparison-expected').innerText(), '25 ± 0.5 ℃');
      await page.locator('#open-criteria').click();
      assert.equal(await page.evaluate(() => document.querySelector('dialog').getBoundingClientRect().width <= innerWidth), true);
      await page.locator('#close-criteria').click();
      await page.screenshot({path:path.join(output,`mobile-${width}.png`), fullPage:true});
      if (await comparison.evaluate(node => node.open)) await comparisonSummary.click();
      assert.equal(await page.locator('.comparison-scroll:visible').count(), 0);
      assert.equal(await page.locator('.follow-up-section').isVisible(), true);
      await page.locator('#search').fill('PA-008');
      assert.equal(await comparison.evaluate(node => node.open), false);
      await comparison.scrollIntoViewIfNeeded();
      await page.screenshot({path:path.join(output,`comparison-collapsed-mobile-${width}.png`)});
      await comparisonSummary.click();
      await page.locator('#collapse-comparison-groups').click();
      assert.equal(await page.locator('.comparison-row:visible').count(),0);
      await page.screenshot({path:path.join(output,`comparison-categories-mobile-${width}.png`)});
      await groupSummary('점도 결과').press('Enter');
      assert.equal(await comparisonGroup('점도 결과').evaluate(node => node.open),true);
      assert.equal(await comparisonGroup('측정 조건').evaluate(node => node.open),false);
      await expandAllComparisonGroups();
      assert.equal(await page.locator('.comparison-scroll:visible').count(),4);
      await page.locator('#search').fill('PA-008');
      await chartPoint('PA-008-M4').click();
      await assertChartSelection('PA-008-M4',1);
      await page.locator('#reset-filter').click();
      await conditionSummary.click();
      await page.locator('#condition-field').selectOption('manufacturingTemperature');
      await page.locator('#condition-limit').check();
      await page.locator('#condition-form [type="submit"]').click();
      assert.equal(await page.locator('#filtered-count').innerText(),'현재 216건 / 전체 1,080건');
      assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth),true);
      const conditionBounds = await page.locator('#condition-form').boundingBox();
      assert.ok(conditionBounds.x >= 0 && conditionBounds.x + conditionBounds.width <= width);
      await page.locator('#condition-explorer').screenshot({path:path.join(output,`condition-filter-mobile-${width}.png`)});
      await page.locator('#clear-condition').click(); await conditionSummary.click();
      await page.locator('#chart-axis').selectOption('field:manufacturingTemperature');
      await page.locator('#chart-y-field').selectOption('sampleTemperature');
      assert.equal(await page.locator('#chart-axis-controls').isVisible(),true);
      assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth),true);
      for (const id of ['chart-axis','chart-y-field']) {
        const bounds=await page.locator(`#${id}`).boundingBox(); assert.ok(bounds.x>=0&&bounds.x+bounds.width<=width);
      }
      await page.locator('.chart-panel').screenshot({path:path.join(output,`chart-axes-mobile-${width}.png`)});
      await page.locator('#reset-filter').click();
    }
    pass('390px·320px 화면에 가로 넘침 없음·기준 창 사용 가능');
    await page.locator('#search').fill('PA-006'); await page.locator('.record-link').nth(1).click();
    await page.locator('#comparison-only-issues').check();
    assert.equal(await page.locator('.comparison-row').count(), 1);
    await page.locator('.comparison-section').scrollIntoViewIfNeeded();
    await page.screenshot({path:path.join(output,'comparison-mobile.png'), fullPage:true});
    await page.locator('.comparison-section').screenshot({path:path.join(output,'comparison-panel-mobile.png')});
    await page.locator('.record-link').first().click();
    await page.locator('.comparison-guide').screenshot({path:path.join(output,'guidance-mobile.png')});
    await page.locator('.follow-up-section').screenshot({path:path.join(output,'checklist-mobile.png')});
    await page.locator('#search').fill('PA-007'); await page.locator('.record-link').first().click();
    await missingTask.locator('input').check(); await missingTask.locator('.follow-up-unavailable').click();
    await missingTask.locator('.follow-up-reason').fill('원본 기록에 측정 온도가 없어 확인할 수 없음');
    await missingTask.locator('.follow-up-reason-category').selectOption('필요한 항목 미기록');
    await page.locator('.follow-up-section').screenshot({path:path.join(output,'unavailable-mobile.png')});
    await page.locator('#unavailable-summary > summary').click();
    await page.locator('#unavailable-summary').screenshot({path:path.join(output,'reason-categories-mobile.png')});
    await page.locator('#manage-reason-categories').click();
    assert.equal(await page.evaluate(() => document.querySelector('#reason-category-dialog').getBoundingClientRect().width <= innerWidth), true);
    await page.locator('#close-reason-categories').click();
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
    const categoryChecksSnapshot = await page.evaluate(() => localStorage.getItem('poly-checklists-demo-20261002'));
    const currentCriteria = await page.evaluate(() => JSON.parse(localStorage.getItem('poly-criteria-v1')));
    const core = await import('../src/core.js');
    const demoRecords = JSON.parse(await fs.readFile(path.resolve(__dirname,'../data/demo-records.json'),'utf8'));
    const categoryChecks = JSON.parse(categoryChecksSnapshot || '{}');
    for (const record of demoRecords.filter(record => record.sampleTemperature === '').slice(0,21)) {
      categoryChecks[record.measurementId] = {signature:core.followUpSignature(record,currentCriteria),outcomes:{'missing:sampleTemperature':{status:'unavailable',reasonCategory:'추가 자료 필요',reason:'페이지 이동 확인용 메모'}}};
    }
    await page.evaluate(checks => localStorage.setItem('poly-checklists-demo-20261002',JSON.stringify(checks)),categoryChecks);
    await page.reload(); await page.waitForFunction(() => document.getElementById('total-count').textContent === '1,080');
    await comparisonSummary.click();
    await page.locator('#unavailable-summary > summary').click();
    await page.locator('#unavailable-filter').selectOption('추가 자료 필요');
    assert.equal(await page.locator('.unavailable-entry').count(),20);
    assert.ok((await page.locator('#unavailable-page-label').innerText()).includes('21개 항목'));
    await page.locator('#unavailable-next').click();
    assert.equal(await page.locator('.unavailable-entry').count(),1);
    await page.locator('#unavailable-previous').click();
    assert.equal(await page.locator('.unavailable-entry').count(),20);
    await page.evaluate(snapshot => localStorage.setItem('poly-checklists-demo-20261002',snapshot),categoryChecksSnapshot);
    pass('이유별 모아보기: 21개 항목의 전체 건수와 페이지 이동');
    assert.deepEqual(errors, []); pass('브라우저 JavaScript·콘솔 오류 없음');
    await fs.writeFile(path.join(output, process.env.PORTABLE_TEST === '1' ? 'portable-results.json' : 'ui-results.json'), JSON.stringify({targetURL,checks,errors},null,2));
  } finally { await browser.close(); }
})().catch(error => { console.error(error); process.exitCode=1; });
